### ISSUE TITLE
Erro de digitação no nome da chave

### ISSUE THREAD

**Issue by rodrigoclira** [williamteles/microservice-WEB2#2]
Imagino que seja 'details'.  Não achei no código o trecho onde usa essa chave, logo não deve estar dando nenhum problema. Contudo, eu resolvi avisar. 

https://github.com/williamteles/microservice-WEB2/blob/18f1f84cc65dff69eb8fea58cb7243ef7ac1c667/authentication_service/authentication/serializers.py#L25

**Comment by williamteles** [comment]
Corrigido no commit: f9d4deae262f4a4eeafcc9461b9e0a0939b95569
